### PR TITLE
feat: allow to edit appVersion in Chart.yaml

### PR DESCRIPTION
**Pull request by giuscri**

### CODE REVIEW

**Comment by giuscri** [comment]
We set appVersion: 0.1.0 for almost every chart we deploy. `helm list` output is less useful than it could be
```
[6/06/22 4:57:57] ➜  ~ helm list
NAME    	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
gluglu  	buyer-area	153     	2022-06-01 11:37:58.180007212 +0000 UTC	deployed	gluglu-0.1.0
gringott	buyer-area	72      	2022-06-06 14:20:46.105505655 +0000 UTC	deployed	gringott-0.1.0	0.1.0
nika    	buyer-area	69      	2022-05-31 15:42:31.121868737 +0000 UTC	deployed	nika-0.1.0    	0.1.0
nika-fe 	buyer-area	179     	2022-05-31 15:46:20.483779394 +0000 UTC	deployed	nika-fe-0.1.0 	0.1.0
nikita  	buyer-area	7       	2022-04-29 16:21:23.105037023 +0000 UTC	deployed	nikita-0.1.0  	0.1.0
```
Why don't we allow kubernetes users to see the deployed git commit at a glance? For example
```
gringott buyer-area 72 2022-06-06 14:20:46.105505655 +0000 UTC deployed gringott-0.1.0 a22fc063
```

**Comment by giuscri** [comment]
Of course we can implement this logic in the single projects' workflows. It was just cool to provide this out of the box as there are no other actions that provide this functionality to my knowledge

**Comment by gi0baro** [comment]
@giuscri let's discuss this in CoP also with @edubacco

**Comment by giuscri** [comment]
OK, I added a card in the Miro board

**Comment by giuscri** [comment]
I forgot to raise the topic in the cop today.

@edubacco any thoughts on this?

**Comment by giuscri** [comment]
We finally discussed it in the CoP today. We agreed it'd be cool to have this but I wasn't able to implement it.

The way this is drafted in this PR wouldn't work: we need to download the chart first

I think a good place to put this logic could be https://github.com/casavo/action-helm-deploy/blob/beca28a336e32e0a4150fe6fc1653a72ac4e989e/action.py#L65-L70 where we could
* download the chart into a tmp directory
* change appVersion `if app_version in specs`
* return the location of the chart in the tmp directory as load_chart() output

What do you think @gi0baro ?

Can you also help me in understanding how that if-clause work?

**Comment by edubacco** [comment]
Since we are not able to update _on the fly_ the appVersion without downloading the chart, I'm starting to think that this step should not be done, as we are hacking a lot how things naturally works.
We were quite aligned on this in the CoP today (but people were very different from the last week one)

**Comment by giuscri** [comment]
OK! Should we close this then?

**Pull request closed without merging**
